const canvas=document.getElementById('simCanvas'),ctx=canvas.getContext('2d');
const tools=[...document.querySelectorAll('.tool')],igniteBtn=document.getElementById('igniteBtn'),pauseBtn=document.getElementById('pauseBtn'),clearBtn=document.getElementById('clearBtn'),particleSlider=document.getElementById('particleCount'),flowScoreEl=document.getElementById('flowScore'),avgSpeedEl=document.getElementById('avgSpeed'),stagnantRateEl=document.getElementById('stagnantRate'),oxygenRateEl=document.getElementById('oxygenRate'),feedbackEl=document.getElementById('feedback');
let selectedTool='wall',drawing=false,running=false,ignited=false,lastTime=performance.now(),densityTimer=0,connectivityDirty=true;
const walls=[],inlets=[],fires=[],chimneys=[];let particles=[];
const CELL=24,MAX_SPEED=125,GRID_COLS=Math.ceil(canvas.width/CELL),GRID_ROWS=Math.ceil(canvas.height/CELL),BUOYANCY=34,COOLING=0.075;
let regionMap=new Int32Array(GRID_COLS*GRID_ROWS),externalRegions=new Set();
function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function snap(v){return Math.floor(v/CELL)*CELL}function hasRect(a,x,y){return a.some(o=>o.x===x&&o.y===y)}function blocked(x,y){return walls.some(w=>x>=w.x&&x<=w.x+CELL&&y>=w.y&&y<=w.y+CELL)}
function rebuildConnectivity(){const wc=new Set(walls.map(w=>Math.floor(w.y/CELL)*GRID_COLS+Math.floor(w.x/CELL)));regionMap=new Int32Array(GRID_COLS*GRID_ROWS);externalRegions=new Set();let id=1;for(let s=0;s<regionMap.length;s++){if(wc.has(s)||regionMap[s])continue;const q=[s],rid=id++;regionMap[s]=rid;let ext=false;for(let i=0;i<q.length;i++){const n=q[i],x=n%GRID_COLS,y=Math.floor(n/GRID_COLS);if(!x||!y||x===GRID_COLS-1||y===GRID_ROWS-1)ext=true;for(const[nx,ny]of[[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){if(nx<0||ny<0||nx>=GRID_COLS||ny>=GRID_ROWS)continue;const ni=ny*GRID_COLS+nx;if(wc.has(ni)||regionMap[ni])continue;regionMap[ni]=rid;q.push(ni)}}if(ext)externalRegions.add(rid)}connectivityDirty=false}
function ensureConnectivity(){if(connectivityDirty)rebuildConnectivity()}function regionAt(x,y){ensureConnectivity();if(x<0||y<0||x>=canvas.width||y>=canvas.height)return 0;return regionMap[Math.floor(y/CELL)*GRID_COLS+Math.floor(x/CELL)]||0}function isExternalPoint(x,y){const r=regionAt(x,y);return r&&externalRegions.has(r)}
function placeAt(p){const x=snap(p.x),y=snap(p.y);if(selectedTool==='wall'){if(!hasRect(walls,x,y)){walls.push({x,y});connectivityDirty=true}}else if(selectedTool==='erase'){for(const a of[walls,inlets,fires,chimneys]){const i=a.findIndex(o=>o.x===x&&o.y===y);if(i>=0){if(a===walls)connectivityDirty=true;a.splice(i,1)}}}else{const a={inlet:inlets,fire:fires,chimney:chimneys}[selectedTool];if(!hasRect(a,x,y))a.push({x,y})}}
tools.forEach(b=>b.addEventListener('click',()=>{tools.forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedTool=b.dataset.tool}));canvas.addEventListener('pointerdown',e=>{drawing=true;canvas.setPointerCapture(e.pointerId);placeAt(pointerPos(e))});canvas.addEventListener('pointermove',e=>{if(drawing&&(selectedTool==='wall'||selectedTool==='erase'))placeAt(pointerPos(e))});canvas.addEventListener('pointerup',()=>drawing=false);canvas.addEventListener('pointercancel',()=>drawing=false);
function targetParticleCount(){return Math.max(20,Number(particleSlider.value)||240)}function randomOpenPoint(r=null){for(let i=0;i<240;i++){const x=8+Math.random()*(canvas.width-16),y=8+Math.random()*(canvas.height-16);if(!blocked(x,y)&&(r===null||regionAt(x,y)===r))return{x,y}}return null}function randomExternalPoint(){for(let i=0;i<300;i++){const p=randomOpenPoint();if(p&&isExternalPoint(p.x,p.y))return p}return{x:8,y:8}}
function makeParticle(p,gas='fresh',temperature=0){return{x:p.x,y:p.y,vx:(Math.random()-.5)*.4,vy:(Math.random()-.5)*.4,gas,temperature,stagnant:0}}
function seedAmbientAir(){ensureConnectivity();particles=Array.from({length:targetParticleCount()},()=>makeParticle(randomExternalPoint()))}function regionParticles(r){return particles.filter(p=>regionAt(p.x,p.y)===r)}function oxygenRatioForRegion(r){if(!r)return 0;if(externalRegions.has(r))return 1;const ps=regionParticles(r);return ps.length?ps.filter(p=>p.gas==='fresh').length/ps.length:0}function fireIntensity(f){if(!ignited)return 0;const o=oxygenRatioForRegion(regionAt(f.x+12,f.y+12));return o<=.12?0:o>=.55?1:(o-.12)/.43}
function forceToward(p,sources,radius,strength){let fx=0,fy=0;const pr=regionAt(p.x,p.y);for(const s of sources){const sx=s.x+12,sy=s.y+12;if(regionAt(sx,sy)!==pr)continue;const dx=sx-p.x,dy=sy-p.y,d=Math.hypot(dx,dy)||1;if(d<radius){const k=(1-d/radius)*strength;fx+=dx/d*k;fy+=dy/d*k}}return{fx,fy}}
function fireForce(p){let fx=0,fy=0;const pr=regionAt(p.x,p.y);for(const f of fires){const cx=f.x+12,cy=f.y+12;if(regionAt(cx,cy)!==pr)continue;const I=fireIntensity(f);if(!I)continue;const dx=p.x-cx,dy=p.y-cy,d=Math.hypot(dx,dy)||1;if(d<300){const k=(1-d/300)*I;fx-=dx/d*18*k;fy-=dy/d*8*k}if(d<145){const heat=(1-d/145)*I;p.temperature=Math.min(1,p.temperature+heat*.055);fy-=14*heat}}return{fx,fy}}
function burnRegion(dt){if(!ignited)return;const byRegion=new Map();for(const f of fires){const r=regionAt(f.x+12,f.y+12);if(r&&!byRegion.has(r))byRegion.set(r,[]);if(r)byRegion.get(r).push(f)}for(const[r,fs]of byRegion){const I=Math.max(...fs.map(f=>fireIntensity(f)));if(!I)continue;const fresh=regionParticles(r).filter(p=>p.gas==='fresh');if(!fresh.length)continue;const rate=(externalRegions.has(r)?.025:.18)*fs.length*I;let budget=rate*dt*fresh.length,whole=Math.floor(budget);if(Math.random()<budget-whole)whole++;whole=Math.max(0,Math.min(fresh.length,whole));fresh.sort((a,b)=>Math.min(...fs.map(f=>Math.hypot(a.x-f.x-12,a.y-f.y-12)))-Math.min(...fs.map(f=>Math.hypot(b.x-f.x-12,b.y-f.y-12))));for(let i=0;i<whole;i++){fresh[i].gas='exhaust';fresh[i].temperature=Math.max(fresh[i].temperature,.9)}}}
function entrainment(p){let fx=0,fy=0,n=0;const r=regionAt(p.x,p.y);for(const q of particles){if(q===p||regionAt(q.x,q.y)!==r)continue;const dx=q.x-p.x,dy=q.y-p.y,d2=dx*dx+dy*dy;if(d2&&d2<11025){const d=Math.sqrt(d2),k=(1-d/105)*.085;fx+=(q.vx-p.vx)*k;fy+=(q.vy-p.vy)*k;if(++n>=20)break}}return{fx,fy}}
function nearestFireCenterX(p){let best=null,dist=Infinity;for(const f of fires){if(regionAt(f.x+12,f.y+12)!==regionAt(p.x,p.y))continue;const d=Math.hypot(p.x-f.x-12,p.y-f.y-12);if(d<dist){dist=d;best=f.x+12}}return best}
function respawn(p){Object.assign(p,makeParticle(randomExternalPoint(),'fresh',0))}
function updateParticle(p,dt){let ax=0,ay=0;if(ignited){let f=fireForce(p);ax+=f.fx;ay+=f.fy;if(inlets.length){f=forceToward(p,inlets,230,8);ax+=f.fx;ay+=f.fy}if(chimneys.length){f=forceToward(p,chimneys,290,22);ax+=f.fx;ay+=f.fy-10}f=entrainment(p);ax+=f.fx;ay+=f.fy;/* Real fix: buoyancy belongs to the hot particle, not to the fire's geometric plume. */ay-=BUOYANCY*p.temperature}
/* Gradual cooling: heated air outside the stove keeps rising for a while, then cools. Exhaust cools more slowly. */const cool=COOLING*(p.gas==='exhaust'?.6:1);p.temperature=Math.max(0,p.temperature-cool*dt);
p.vx*=Math.pow(.994,dt*60);p.vy*=Math.pow(.994,dt*60);p.vx+=ax*dt;p.vy+=ay*dt;const sp=Math.hypot(p.vx,p.vy);if(sp>MAX_SPEED){p.vx=p.vx/sp*MAX_SPEED;p.vy=p.vy/sp*MAX_SPEED}
const ox=p.x,oy=p.y,nx=ox+p.vx*dt,ny=oy+p.vy*dt;const hitX=blocked(nx,p.y);if(hitX){p.vx*=-.16}else p.x=nx;const upwardBefore=p.vy<0,hitY=blocked(p.x,ny);if(hitY){/* Upward hot flow hitting a ceiling converts part of vertical momentum into lateral spreading. */if(upwardBefore&&p.temperature>.08){const cx=nearestFireCenterX(p);let dir=cx===null?(Math.random()<.5?-1:1):Math.sign(p.x-cx);if(!dir)dir=Math.random()<.5?-1:1;const spread=Math.max(8,Math.min(42,Math.abs(p.vy)*.7+22*p.temperature));p.vx+=dir*spread;p.vy=Math.abs(p.vy)*.06}else p.vy*=-.12}else p.y=ny;if(blocked(p.x,p.y)){p.x=ox;p.y=oy;p.vx*=.08;p.vy*=.08}
const cs=Math.hypot(p.vx,p.vy);p.stagnant=cs<3?p.stagnant+dt:Math.max(0,p.stagnant-dt*.7);const r=regionAt(p.x,p.y);if(p.gas==='exhaust'&&externalRegions.has(r)&&Math.random()<dt*.12){p.gas='fresh';p.temperature*=.75}if(p.x<0||p.x>=canvas.width||p.y<0||p.y>=canvas.height)respawn(p)}
/* No teleport-style density correction inside sealed chambers. Only outside air may be lightly re-seeded for visual coverage. */function redistribute(){if(!ignited)return;const regions=[...new Set(particles.map(p=>regionAt(p.x,p.y)).filter(Boolean))];for(const r of regions){if(!externalRegions.has(r))continue;const ps=regionParticles(r);if(ps.length<8)continue;const moved=Math.max(1,Math.floor(ps.length*.004));for(let i=0;i<moved;i++){const p=ps[Math.floor(Math.random()*ps.length)],pt=randomOpenPoint(r);if(pt&&p.temperature<.05){p.x=pt.x;p.y=pt.y;p.vx*=.2;p.vy*=.2}}}}
function drawGrid(){ctx.strokeStyle='rgba(148,163,184,.16)';ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=CELL){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=CELL){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}
function drawCells(a,c,l){ctx.fillStyle=c;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='16px system-ui';for(const o of a){ctx.fillRect(o.x+1,o.y+1,22,22);if(l){ctx.fillStyle='#fff';ctx.fillText(l,o.x+12,o.y+12);ctx.fillStyle=c}}}
function drawFires(){ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='16px system-ui';for(const f of fires){const I=fireIntensity(f);ctx.fillStyle=I?`rgba(234,88,12,${.35+.65*I})`:'#6b7280';ctx.fillRect(f.x+1,f.y+1,22,22);ctx.fillStyle='#fff';ctx.fillText(I?'🔥':'✕',f.x+12,f.y+12)}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);drawGrid();drawCells(walls,'#374151','');drawCells(inlets,'#2563eb','↔');drawFires();drawCells(chimneys,'#7c3aed','↑');for(const p of particles){const sp=Math.hypot(p.vx,p.vy);ctx.beginPath();ctx.arc(p.x,p.y,Math.min(4.8,2+sp/42),0,Math.PI*2);ctx.fillStyle=p.gas==='exhaust'?'rgba(75,85,99,.88)':p.temperature>.12?'rgba(234,88,12,.80)':'rgba(37,99,235,.52)';ctx.fill()}}
function summary(){const rs=[...new Set(fires.map(f=>regionAt(f.x+12,f.y+12)).filter(Boolean))];if(!rs.length)return{oxygen:0,external:false,burning:false,exhaust:0};const oxygen=Math.min(...rs.map(oxygenRatioForRegion)),external=rs.some(r=>externalRegions.has(r)),burning=fires.some(f=>fireIntensity(f)>0),ps=rs.flatMap(regionParticles),exhaust=ps.length?ps.filter(p=>p.gas==='exhaust').length/ps.length:0;return{oxygen,external,burning,exhaust}}
function updateMetrics(){if(!ignited||!particles.length)return;const speeds=particles.map(p=>Math.hypot(p.vx,p.vy)),avg=speeds.reduce((a,b)=>a+b,0)/speeds.length,st=particles.filter(p=>p.stagnant>.8).length/particles.length,s=summary(),score=Math.max(0,Math.min(100,Math.round((inlets.length?10:0)+(fires.length?10:0)+(chimneys.length?18:0)+Math.min(45,avg/55*45)-st*32-(s.external?0:(1-s.oxygen)*22)+18)));flowScoreEl.textContent=score+' / 100';avgSpeedEl.textContent=avg.toFixed(1)+'（相對值）';stagnantRateEl.textContent=Math.round(st*100)+'%';if(oxygenRateEl)oxygenRateEl.textContent=Math.round(s.oxygen*100)+'%';if(!fires.length)feedbackEl.textContent='目前沒有火源。';else if(!s.burning)feedbackEl.textContent=`氧氣不足，火源已熄滅。封閉區約 ${Math.round(s.exhaust*100)}% 示蹤粒子已成為燃燒後氣體。`;else if(!s.external)feedbackEl.textContent=`燃燒區封閉：新鮮空氣約 ${Math.round(s.oxygen*100)}%，燃燒後氣體約 ${Math.round(s.exhaust*100)}%，熱氣撞到頂部後會向兩側展開。`;else feedbackEl.textContent='受熱粒子離開火源後仍有浮力，會持續上升並逐漸冷卻。'}
function loop(now){const dt=Math.min(.033,(now-lastTime)/1000);lastTime=now;if(running&&ignited){burnRegion(dt);particles.forEach(p=>updateParticle(p,dt));densityTimer+=dt;if(densityTimer>=.28){redistribute();densityTimer=0}updateMetrics()}draw();requestAnimationFrame(loop)}
igniteBtn.addEventListener('click',()=>{ensureConnectivity();ignited=true;running=true;lastTime=performance.now();igniteBtn.textContent='🔥 已點火';pauseBtn.textContent='暫停'});pauseBtn.addEventListener('click',()=>{if(ignited){running=!running;lastTime=performance.now();pauseBtn.textContent=running?'暫停':'繼續'}});clearBtn.addEventListener('click',()=>{walls.length=inlets.length=fires.length=chimneys.length=0;ignited=running=false;connectivityDirty=true;rebuildConnectivity();seedAmbientAir();igniteBtn.textContent='🔥 點火';flowScoreEl.textContent=avgSpeedEl.textContent=stagnantRateEl.textContent='—';if(oxygenRateEl)oxygenRateEl.textContent='—';feedbackEl.textContent='周圍已充滿空氣。先設計火箭爐，再按「點火」。'});particleSlider.addEventListener('input',()=>{const n=targetParticleCount();if(particles.length>n)particles.length=n;while(particles.length<n)particles.push(makeParticle(randomExternalPoint()))});rebuildConnectivity();seedAmbientAir();requestAnimationFrame(loop);