const canvas=document.getElementById('simCanvas'),ctx=canvas.getContext('2d');
const tools=[...document.querySelectorAll('.tool')],igniteBtn=document.getElementById('igniteBtn'),pauseBtn=document.getElementById('pauseBtn'),clearBtn=document.getElementById('clearBtn'),particleSlider=document.getElementById('particleCount'),flowScoreEl=document.getElementById('flowScore'),avgSpeedEl=document.getElementById('avgSpeed'),stagnantRateEl=document.getElementById('stagnantRate'),oxygenRateEl=document.getElementById('oxygenRate'),feedbackEl=document.getElementById('feedback');
let selectedTool='wall',drawing=false,running=false,ignited=false,lastTime=performance.now(),densityTimer=0,reservoirTimer=0,connectivityDirty=true;
const walls=[],inlets=[],fires=[],chimneys=[];let particles=[];
const CELL=24,GRID_COLS=Math.ceil(canvas.width/CELL),GRID_ROWS=Math.ceil(canvas.height/CELL),MAX_SPEED=125,BUOYANCY=34,COOLING=.075,MAX_PARTICLES_PER_CELL=4,DENSITY_PRESSURE=8.5,DENSITY_INTERVAL=.08,RESERVOIR_INTERVAL=.10,AMBIENT_DENSITY=.45,MAX_BOUNDARY_INFLOW_PER_TICK=6;
let regionMap=new Int32Array(GRID_COLS*GRID_ROWS),externalRegions=new Set(),densitySnapshot=new Int16Array(GRID_COLS*GRID_ROWS);
function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function snap(v){return Math.floor(v/CELL)*CELL}function hasRect(a,x,y){return a.some(o=>o.x===x&&o.y===y)}function blocked(x,y){return walls.some(w=>x>=w.x&&x<=w.x+CELL&&y>=w.y&&y<=w.y+CELL)}function cellIndexXY(x,y){if(x<0||y<0||x>=canvas.width||y>=canvas.height)return-1;return Math.floor(y/CELL)*GRID_COLS+Math.floor(x/CELL)}function pointInCell(i){const x=i%GRID_COLS,y=Math.floor(i/GRID_COLS),p=4;return{x:x*CELL+p+Math.random()*(CELL-p*2),y:y*CELL+p+Math.random()*(CELL-p*2)}}function wallCellSet(){return new Set(walls.map(w=>Math.floor(w.y/CELL)*GRID_COLS+Math.floor(w.x/CELL)))}
function rebuildConnectivity(){const wc=wallCellSet();regionMap=new Int32Array(GRID_COLS*GRID_ROWS);externalRegions=new Set();let id=1;for(let s=0;s<regionMap.length;s++){if(wc.has(s)||regionMap[s])continue;const r=id++,q=[s];regionMap[s]=r;let ext=false;for(let k=0;k<q.length;k++){const i=q[k],x=i%GRID_COLS,y=Math.floor(i/GRID_COLS);if(!x||!y||x===GRID_COLS-1||y===GRID_ROWS-1)ext=true;for(const[nx,ny]of[[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){if(nx<0||ny<0||nx>=GRID_COLS||ny>=GRID_ROWS)continue;const ni=ny*GRID_COLS+nx;if(wc.has(ni)||regionMap[ni])continue;regionMap[ni]=r;q.push(ni)}}if(ext)externalRegions.add(r)}connectivityDirty=false}function ensureConnectivity(){if(connectivityDirty)rebuildConnectivity()}function regionAt(x,y){ensureConnectivity();const i=cellIndexXY(x,y);return i>=0?(regionMap[i]||0):0}
function placeAt(p){const x=snap(p.x),y=snap(p.y);if(selectedTool==='wall'){if(!hasRect(walls,x,y)){walls.push({x,y});connectivityDirty=true}return}if(selectedTool==='erase'){for(const a of[walls,inlets,fires,chimneys]){const i=a.findIndex(o=>o.x===x&&o.y===y);if(i>=0){if(a===walls)connectivityDirty=true;a.splice(i,1)}}return}const a={inlet:inlets,fire:fires,chimney:chimneys}[selectedTool];if(a&&!hasRect(a,x,y))a.push({x,y})}
tools.forEach(b=>b.addEventListener('click',()=>{tools.forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedTool=b.dataset.tool}));canvas.addEventListener('pointerdown',e=>{drawing=true;canvas.setPointerCapture(e.pointerId);placeAt(pointerPos(e))});canvas.addEventListener('pointermove',e=>{if(drawing&&(selectedTool==='wall'||selectedTool==='erase'))placeAt(pointerPos(e))});canvas.addEventListener('pointerup',()=>drawing=false);canvas.addEventListener('pointercancel',()=>drawing=false);
function targetParticleCount(){return Math.max(20,Number(particleSlider.value)||240)}function makeParticle(p,gas='fresh',temperature=0){return{x:p.x,y:p.y,vx:(Math.random()-.5)*.4,vy:(Math.random()-.5)*.4,gas,temperature,stagnant:0}}function externalOpenCells(){ensureConnectivity();const wc=wallCellSet(),a=[];for(let i=0;i<regionMap.length;i++)if(!wc.has(i)&&externalRegions.has(regionMap[i]))a.push(i);return a}function boundaryOpenCells(){ensureConnectivity();const wc=wallCellSet(),a=[];for(let i=0;i<regionMap.length;i++){if(wc.has(i))continue;const x=i%GRID_COLS,y=Math.floor(i/GRID_COLS);if(x&&y&&x!==GRID_COLS-1&&y!==GRID_ROWS-1)continue;if(externalRegions.has(regionMap[i]))a.push(i)}return a}function buildDensity(){const c=new Int16Array(GRID_COLS*GRID_ROWS);for(const p of particles){const i=cellIndexXY(p.x,p.y);if(i>=0)c[i]++}return c}
function seedAmbientAir(){ensureConnectivity();const cells=externalOpenCells();particles=[];if(!cells.length)return;for(let i=cells.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cells[i],cells[j]]=[cells[j],cells[i]]}const n=targetParticleCount();for(let i=0;i<n;i++)particles.push(makeParticle(pointInCell(cells[i%cells.length])))}
function boundarySpawnPoint(){const cells=boundaryOpenCells();if(!cells.length)return null;const counts=buildDensity();let min=Infinity,pool=[];for(const i of cells){const n=counts[i];if(n>=MAX_PARTICLES_PER_CELL)continue;if(n<min){min=n;pool=[i]}else if(n===min)pool.push(i)}if(!pool.length)return null;const i=pool[Math.floor(Math.random()*pool.length)],x=i%GRID_COLS,y=Math.floor(i/GRID_COLS);let px=x*CELL+CELL/2,py=y*CELL+CELL/2,vx=0,vy=0;if(x===0){px=1;vx=7+Math.random()*5}else if(x===GRID_COLS-1){px=canvas.width-1;vx=-(7+Math.random()*5)}if(y===0){py=1;vy=7+Math.random()*5}else if(y===GRID_ROWS-1){py=canvas.height-1;vy=-(7+Math.random()*5)}return{x:px,y:py,vx,vy}}
function addBoundaryParticle(){const s=boundarySpawnPoint();if(!s)return false;const p=makeParticle({x:s.x,y:s.y});p.vx=s.vx+(Math.random()-.5);p.vy=s.vy+(Math.random()-.5);particles.push(p);return true}
function respawnFromBoundary(p){const s=boundarySpawnPoint();if(!s)return;Object.assign(p,makeParticle({x:s.x,y:s.y}));p.vx=s.vx+(Math.random()-.5);p.vy=s.vy+(Math.random()-.5)}
/* Open air is an infinite reservoir.  Only boundary cells may create new tracers. Closed regions never receive them. */function maintainExternalReservoir(){ensureConnectivity();const cells=externalOpenCells();if(!cells.length)return;let externalCount=0;for(const p of particles)if(externalRegions.has(regionAt(p.x,p.y)))externalCount++;const baseline=Math.max(targetParticleCount(),Math.ceil(cells.length*AMBIENT_DENSITY));const deficit=Math.max(0,baseline-externalCount);const add=Math.min(MAX_BOUNDARY_INFLOW_PER_TICK,deficit);for(let i=0;i<add;i++)if(!addBoundaryParticle())break}
function regionParticles(r){return particles.filter(p=>regionAt(p.x,p.y)===r)}function oxygenRatioForRegion(r){if(!r)return 0;if(externalRegions.has(r))return 1;const ps=regionParticles(r);return ps.length?ps.filter(p=>p.gas==='fresh').length/ps.length:0}function fireIntensity(f){if(!ignited)return 0;const o=oxygenRatioForRegion(regionAt(f.x+CELL/2,f.y+CELL/2));return o<=.12?0:o>=.55?1:(o-.12)/.43}
function forceToward(p,a,radius,strength){let fx=0,fy=0;const r=regionAt(p.x,p.y);for(const s of a){const x=s.x+CELL/2,y=s.y+CELL/2;if(regionAt(x,y)!==r)continue;const dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy)||1;if(d<radius){const k=(1-d/radius)*strength;fx+=dx/d*k;fy+=dy/d*k}}return{fx,fy}}
function fireForce(p){let fx=0,fy=0;const r=regionAt(p.x,p.y);for(const f of fires){const x=f.x+CELL/2,y=f.y+CELL/2;if(regionAt(x,y)!==r)continue;const I=fireIntensity(f);if(!I)continue;const dx=p.x-x,dy=p.y-y,d=Math.hypot(dx,dy)||1;if(d<300){const k=(1-d/300)*I;fx-=dx/d*18*k;fy-=dy/d*8*k}if(d<145){const h=(1-d/145)*I;p.temperature=Math.min(1,p.temperature+h*.055);fy-=14*h}}return{fx,fy}}
function burnRegion(dt){if(!ignited)return;const m=new Map();for(const f of fires){const r=regionAt(f.x+CELL/2,f.y+CELL/2);if(!r)continue;if(!m.has(r))m.set(r,[]);m.get(r).push(f)}for(const[r,fs]of m){const I=Math.max(...fs.map(fireIntensity));if(!I)continue;const fresh=regionParticles(r).filter(p=>p.gas==='fresh');if(!fresh.length)continue;const rate=(externalRegions.has(r)?.025:.18)*fs.length*I;let n=Math.floor(rate*dt*fresh.length);if(Math.random()<rate*dt*fresh.length-n)n++;n=Math.min(n,fresh.length);fresh.sort((a,b)=>Math.min(...fs.map(f=>Math.hypot(a.x-f.x-CELL/2,a.y-f.y-CELL/2)))-Math.min(...fs.map(f=>Math.hypot(b.x-f.x-CELL/2,b.y-f.y-CELL/2))));for(let i=0;i<n;i++){fresh[i].gas='exhaust';fresh[i].temperature=Math.max(fresh[i].temperature,.9)}}}
function entrainment(p){let fx=0,fy=0,n=0;const r=regionAt(p.x,p.y);for(const q of particles){if(q===p||regionAt(q.x,q.y)!==r)continue;const dx=q.x-p.x,dy=q.y-p.y,d2=dx*dx+dy*dy;if(d2&&d2<11025){const d=Math.sqrt(d2),k=(1-d/105)*.085;fx+=(q.vx-p.vx)*k;fy+=(q.vy-p.vy)*k;if(++n>=20)break}}return{fx,fy}}
function densityPressure(p){const i=cellIndexXY(p.x,p.y);if(i<0)return{fx:0,fy:0};const x=i%GRID_COLS,y=Math.floor(i/GRID_COLS),r=regionMap[i],here=densitySnapshot[i]||0;let fx=0,fy=0;for(const[dx,dy]of[[-1,0],[1,0],[0,-1],[0,1]]){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=GRID_COLS||ny>=GRID_ROWS)continue;const ni=ny*GRID_COLS+nx;if(!r||regionMap[ni]!==r)continue;const g=here-(densitySnapshot[ni]||0);fx+=dx*g*DENSITY_PRESSURE;fy+=dy*g*DENSITY_PRESSURE}return{fx,fy}}
function nearestFireCenterX(p){let best=null,d0=Infinity,r=regionAt(p.x,p.y);for(const f of fires){if(regionAt(f.x+CELL/2,f.y+CELL/2)!==r)continue;const d=Math.hypot(p.x-f.x-CELL/2,p.y-f.y-CELL/2);if(d<d0){d0=d;best=f.x+CELL/2}}return best}
function updateParticle(p,dt){let ax=0,ay=0;if(ignited){let f=fireForce(p);ax+=f.fx;ay+=f.fy;if(inlets.length){f=forceToward(p,inlets,230,8);ax+=f.fx;ay+=f.fy}if(chimneys.length){f=forceToward(p,chimneys,290,22);ax+=f.fx;ay+=f.fy-10}f=entrainment(p);ax+=f.fx;ay+=f.fy;f=densityPressure(p);ax+=f.fx;ay+=f.fy;ay-=BUOYANCY*p.temperature}p.temperature=Math.max(0,p.temperature-COOLING*(p.gas==='exhaust'?.6:1)*dt);p.vx*=Math.pow(.994,dt*60);p.vy*=Math.pow(.994,dt*60);p.vx+=ax*dt;p.vy+=ay*dt;const sp=Math.hypot(p.vx,p.vy);if(sp>MAX_SPEED){p.vx=p.vx/sp*MAX_SPEED;p.vy=p.vy/sp*MAX_SPEED}const ox=p.x,oy=p.y,nx=ox+p.vx*dt,ny=oy+p.vy*dt;if(blocked(nx,p.y))p.vx*=-.16;else p.x=nx;const up=p.vy<0;if(blocked(p.x,ny)){if(up&&p.temperature>.08){const cx=nearestFireCenterX(p);let dir=cx===null?(Math.random()<.5?-1:1):Math.sign(p.x-cx);if(!dir)dir=Math.random()<.5?-1:1;p.vx+=dir*Math.max(8,Math.min(42,Math.abs(p.vy)*.7+22*p.temperature));p.vy=Math.abs(p.vy)*.06}else p.vy*=-.12}else p.y=ny;if(blocked(p.x,p.y)){p.x=ox;p.y=oy;p.vx*=.08;p.vy*=.08}const s=Math.hypot(p.vx,p.vy);p.stagnant=s<3?p.stagnant+dt:Math.max(0,p.stagnant-dt*.7);const r=regionAt(p.x,p.y);if(p.gas==='exhaust'&&externalRegions.has(r)&&Math.random()<dt*.12){p.gas='fresh';p.temperature*=.75}if(p.x<0||p.x>=canvas.width||p.y<0||p.y>=canvas.height)respawnFromBoundary(p)}
function enforceCellCapacity(){ensureConnectivity();for(let pass=0;pass<2;pass++){const b=Array.from({length:GRID_COLS*GRID_ROWS},()=>[]),c=new Int16Array(GRID_COLS*GRID_ROWS);for(const p of particles){const i=cellIndexXY(p.x,p.y);if(i>=0){b[i].push(p);c[i]++}}for(let i=0;i<b.length;i++){if(b[i].length<=MAX_PARTICLES_PER_CELL)continue;const x=i%GRID_COLS,y=Math.floor(i/GRID_COLS),r=regionMap[i];for(const p of b[i].slice(MAX_PARTICLES_PER_CELL)){let best=-1,n=Infinity;for(const[dx,dy]of[[-1,0],[1,0],[0,-1],[0,1]]){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=GRID_COLS||ny>=GRID_ROWS)continue;const ni=ny*GRID_COLS+nx;if(!r||regionMap[ni]!==r||c[ni]>=MAX_PARTICLES_PER_CELL)continue;if(c[ni]<n){best=ni;n=c[ni]}}if(best>=0){const q=pointInCell(best);p.x=q.x;p.y=q.y;p.vx*=.35;p.vy*=.35;c[i]--;c[best]++}else{p.vx+=(Math.random()-.5)*8;p.vy+=(Math.random()-.5)*8}}}}}
function drawGrid(){ctx.strokeStyle='rgba(148,163,184,.16)';ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=CELL){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=CELL){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}function drawCells(a,c,l){ctx.fillStyle=c;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='16px system-ui';for(const o of a){ctx.fillRect(o.x+1,o.y+1,CELL-2,CELL-2);if(l){ctx.fillStyle='#fff';ctx.fillText(l,o.x+CELL/2,o.y+CELL/2);ctx.fillStyle=c}}}function drawFires(){ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='16px system-ui';for(const f of fires){const I=fireIntensity(f);ctx.fillStyle=I?`rgba(234,88,12,${.35+.65*I})`:'#6b7280';ctx.fillRect(f.x+1,f.y+1,CELL-2,CELL-2);ctx.fillStyle='#fff';ctx.fillText(I?'🔥':'✕',f.x+CELL/2,f.y+CELL/2)}}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);drawGrid();drawCells(walls,'#374151','');drawCells(inlets,'#2563eb','↔');drawFires();drawCells(chimneys,'#7c3aed','↑');for(const p of particles){const s=Math.hypot(p.vx,p.vy);ctx.beginPath();ctx.arc(p.x,p.y,Math.min(4.8,2+s/42),0,Math.PI*2);ctx.fillStyle=p.gas==='exhaust'?'rgba(75,85,99,.88)':p.temperature>.12?'rgba(234,88,12,.80)':'rgba(37,99,235,.52)';ctx.fill()}}
function summary(){const rs=[...new Set(fires.map(f=>regionAt(f.x+CELL/2,f.y+CELL/2)).filter(Boolean))];if(!rs.length)return{oxygen:0,external:false,burning:false,exhaust:0};const oxygen=Math.min(...rs.map(oxygenRatioForRegion)),external=rs.some(r=>externalRegions.has(r)),burning=fires.some(f=>fireIntensity(f)>0),ps=rs.flatMap(regionParticles),exhaust=ps.length?ps.filter(p=>p.gas==='exhaust').length/ps.length:0;return{oxygen,external,burning,exhaust}}
function updateMetrics(){if(!ignited||!particles.length)return;const speeds=particles.map(p=>Math.hypot(p.vx,p.vy)),avg=speeds.reduce((a,b)=>a+b,0)/speeds.length,st=particles.filter(p=>p.stagnant>.8).length/particles.length,s=summary();const score=Math.max(0,Math.min(100,Math.round((inlets.length?10:0)+(fires.length?10:0)+(chimneys.length?18:0)+Math.min(45,avg/55*45)-st*32-(s.external?0:(1-s.oxygen)*22)+18)));flowScoreEl.textContent=score+' / 100';avgSpeedEl.textContent=avg.toFixed(1)+'（相對值）';stagnantRateEl.textContent=Math.round(st*100)+'%';if(oxygenRateEl)oxygenRateEl.textContent=Math.round(s.oxygen*100)+'%';if(!fires.length)feedbackEl.textContent='目前沒有火源。';else if(!s.burning)feedbackEl.textContent=`氧氣不足，火源已熄滅。封閉區約 ${Math.round(s.exhaust*100)}% 為燃燒後氣體。`;else if(!s.external)feedbackEl.textContent=`燃燒區封閉：不會由外界補入空氣；新鮮空氣約 ${Math.round(s.oxygen*100)}%。`;else feedbackEl.textContent=`燃燒區與外界連通：外界視為無限空氣庫，低密度時會持續由畫布邊界補氣。每格最多 ${MAX_PARTICLES_PER_CELL} 顆。`}
function loop(now){const dt=Math.min(.033,(now-lastTime)/1000);lastTime=now;if(running&&ignited){burnRegion(dt);densitySnapshot=buildDensity();particles.forEach(p=>updateParticle(p,dt));densityTimer+=dt;reservoirTimer+=dt;if(densityTimer>=DENSITY_INTERVAL){enforceCellCapacity();densityTimer=0}if(reservoirTimer>=RESERVOIR_INTERVAL){maintainExternalReservoir();reservoirTimer=0}updateMetrics()}draw();requestAnimationFrame(loop)}
igniteBtn.addEventListener('click',()=>{ensureConnectivity();ignited=true;running=true;lastTime=performance.now();densityTimer=reservoirTimer=0;igniteBtn.textContent='🔥 已點火';pauseBtn.textContent='暫停'});pauseBtn.addEventListener('click',()=>{if(!ignited)return;running=!running;lastTime=performance.now();pauseBtn.textContent=running?'暫停':'繼續'});clearBtn.addEventListener('click',()=>{walls.length=inlets.length=fires.length=chimneys.length=0;ignited=running=false;densityTimer=reservoirTimer=0;connectivityDirty=true;rebuildConnectivity();seedAmbientAir();igniteBtn.textContent='🔥 點火';pauseBtn.textContent='暫停';flowScoreEl.textContent=avgSpeedEl.textContent=stagnantRateEl.textContent='—';if(oxygenRateEl)oxygenRateEl.textContent='—';feedbackEl.textContent='周圍已充滿空氣。先設計火箭爐，再按「點火」。'});particleSlider.addEventListener('input',()=>{const target=targetParticleCount();if(particles.length>target)particles.length=target;while(particles.length<target)if(!addBoundaryParticle())break;enforceCellCapacity()});rebuildConnectivity();seedAmbientAir();requestAnimationFrame(loop);
